turbo: 'fast_and_furious/turbo.mp3'
nanja: 'fast_and_furious/nanja.mp3'
motor: 'fast_and_furious/motor.mp3'
osewa: 'fast_and_furious/osewa.mp3'
tomica: 'fast_and_furious/tomica.mp3'
gulliver: 'fast_and_furious/gulliver.mp3'